<testsuites name="results">
  <testsuite name="all" package="all">
    <property name="random_seed" value="1752697872" />
    <testcase name="single_byte" classname="test_uart_tx" file="/home/imp/work/uart/test/test_uart_tx.py" lineno="87" time="9.58065938949585" sim_time_ns="989637.001" ratio_time="103295.29114509898">
      <failure message="Test failed with RANDOM_SEED=123" />
    </testcase>
    <testcase name="tx_sequence" classname="test_uart_tx" file="/home/imp/work/uart/test/test_uart_tx.py" lineno="118" time="75550.99472856522" sim_time_ns="8908320.0" ratio_time="117.9113528816562">
      <failure message="Test failed with RANDOM_SEED=123" />
    </testcase>
    <testcase name="baud_change" classname="test_uart_tx" file="/home/imp/work/uart/test/test_uart_tx.py" lineno="142" time="0" sim_time_ns="0" ratio_time="nan">
      <failure message="Test failed with RANDOM_SEED=123" />
    </testcase>
    <testcase name="tx_abort" classname="test_uart_tx" file="/home/imp/work/uart/test/test_uart_tx.py" lineno="171" time="0" sim_time_ns="0" ratio_time="nan">
      <failure message="Test failed with RANDOM_SEED=123" />
    </testcase>
    <testcase name="overflow" classname="test_uart_tx" file="/home/imp/work/uart/test/test_uart_tx.py" lineno="198" time="0" sim_time_ns="0" ratio_time="nan">
      <failure message="Test failed with RANDOM_SEED=123" />
    </testcase>
  </testsuite>
</testsuites>
